const _flags = {
  'Armenia': '🇦🇲',
  'Australia': '🇦🇺',
  'Austria': '🇦🇹',
  'Belarus': '🇧🇾',
  'Croatia': '🇭🇷',
  'Cyprus': '🇨🇾',
  'Czech Republic': '🇨🇿',
  'Finland': '🇫🇮',
  'Georgia': '🇬🇪',
  'Greece': '🇬🇷',
  'Hungary': '🇭🇺',
  'Indonesia': '🇮🇩',
  'Italy': '🇮🇹',
  'Latvia': '🇱🇻',
  'Lithuania': '🇱🇹',
  'Montenegro': '🇲🇪',
  'Northern Cyprus': '🇹🇷',
  'Poland': '🇵🇱',
  'Portugal': '🇵🇹',
  'Russia': '🇷🇺',
  'Serbia': '🇷🇸',
  'Spain': '🇪🇸',
  'Thailand': '🇹🇭',
  'Turkey': '🇹🇷',
  'UAE': '🇦🇪',
  'Uzbekistan': '🇺🇿',
};

String flagFor(String country) => _flags[country] ?? '🏙️';
